version: '3.9'

services:
  app:
    container_name: oknawa_api
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/usr/src/app
      - ./.env:/usr/src/app/.env
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - oknawa-network

  db:
    container_name: oknawa_db
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5433:5432
    networks:
      - oknawa-network

volumes:
  postgres_data:

networks:
  oknawa-network: