version: '3.9'

services:
  app:
    container_name: oknawa_api
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    env_file:
      - env/base.env
    networks:
      - oknawa-network

  db:
    container_name: oknawa_db
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/base.env
    ports:
      - 5432:5432
    networks:
      - oknawa-network

  redis:
    container_name: oknawa_redis
    image: redis:6.0-alpine
    env_file:
      - env/base.env
    ports:
      - 6379:6379
    networks:
      - oknawa-network

volumes:
  postgres_data:

networks:
  oknawa-network: