"""PopularMeetingLocation table create

Revision ID: f96f41032ef0
Revises: c7d7af19a559
Create Date: 2023-11-26 05:13:52.245371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f96f41032ef0'
down_revision: Union[str, None] = 'c7d7af19a559'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('popular_meeting_location',
    sa.Column('id', sa.Integer(), nullable=False, comment='PK'),
    sa.Column('name', sa.String(), nullable=False, comment='위치 이름'),
    sa.Column('type', sa.String(), nullable=False, comment='위치 타입'),
    sa.Column('url', sa.String(), nullable=False, comment='위치 url'),
    sa.Column('address', sa.String(), nullable=False, comment='위치 주소'),
    sa.Column('location_x', sa.String(), nullable=False, comment='x좌표'),
    sa.Column('location_y', sa.String(), nullable=False, comment='y좌표'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='수정일시'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='삭제일시'),
    sa.PrimaryKeyConstraint('id'),
    comment='인기 있는 만남의 장소'
    )
    op.create_index(op.f('ix_popular_meeting_location_id'), 'popular_meeting_location', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_popular_meeting_location_id'), table_name='popular_meeting_location')
    op.drop_table('popular_meeting_location')
    # ### end Alembic commands ###
